# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
operator_count = 1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 428)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.expression = QtWidgets.QLabel(self.centralwidget)
        self.expression.setGeometry(QtCore.QRect(0, 0, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.expression.setFont(font)
        self.expression.setStyleSheet("background-color:white;")
        self.expression.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.expression.setObjectName("expression")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(0, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color:white;")
        self.result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result.setText("0")
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.zero = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("0"))
        self.zero.setGeometry(QtCore.QRect(10, 380, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.zero.setFont(font)
        self.zero.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#zero {\n"
"   border: 1px solid gray;\n"
"}\n"
"#zero:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.zero.setObjectName("zero")
        self.dot = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.decimal_pressed())
        self.dot.setGeometry(QtCore.QRect(110, 380, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.dot.setFont(font)
        self.dot.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#dot{\n"
"   border: 1px solid gray;\n"
"}\n"
"#dot:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.dot.setObjectName("dot")
        self.one = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("1"))
        self.one.setGeometry(QtCore.QRect(10, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.one.setFont(font)
        self.one.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#one{\n"
"   border: 1px solid gray;\n"
"}\n"
"#one:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("2"))
        self.two.setGeometry(QtCore.QRect(60, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.two.setFont(font)
        self.two.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#two{\n"
"   border: 1px solid gray;\n"
"}\n"
"#two:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("3"))
        self.three.setGeometry(QtCore.QRect(110, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.three.setFont(font)
        self.three.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#three{\n"
"   border: 1px solid gray;\n"
"}\n"
"#three:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.three.setObjectName("three")
        self.plus = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("+"))
        self.plus.setGeometry(QtCore.QRect(160, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.plus.setFont(font)
        self.plus.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#plus{\n"
"   border: 1px solid gray;\n"
"}\n"
"#plus:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("-"))
        self.minus.setGeometry(QtCore.QRect(210, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.minus.setFont(font)
        self.minus.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#minus{\n"
"   border: 1px solid gray;\n"
"}\n"
"#minus:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.minus.setObjectName("minus")
        self.six = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("6"))
        self.six.setGeometry(QtCore.QRect(110, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.six.setFont(font)
        self.six.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#six{\n"
"   border: 1px solid gray;\n"
"}\n"
"#six:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.six.setObjectName("six")
        self.divide = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("/"))
        self.divide.setGeometry(QtCore.QRect(210, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.divide.setFont(font)
        self.divide.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#divide{\n"
"   border: 1px solid gray;\n"
"}\n"
"#divide:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.divide.setObjectName("divide")
        self.multiply = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("*"))
        self.multiply.setGeometry(QtCore.QRect(160, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.multiply.setFont(font)
        self.multiply.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#multiply{\n"
"   border: 1px solid gray;\n"
"}\n"
"#multiply:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.multiply.setObjectName("multiply")
        self.four = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("4"))
        self.four.setGeometry(QtCore.QRect(10, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.four.setFont(font)
        self.four.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#four{\n"
"   border: 1px solid gray;\n"
"}\n"
"#four:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("5"))
        self.five.setGeometry(QtCore.QRect(60, 280, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.five.setFont(font)
        self.five.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#five{\n"
"   border: 1px solid gray;\n"
"}\n"
"#five:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.five.setObjectName("five")
        self.seven = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("7"))
        self.seven.setGeometry(QtCore.QRect(10, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.seven.setFont(font)
        self.seven.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#seven{\n"
"   border: 1px solid gray;\n"
"}\n"
"#seven:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.seven.setObjectName("seven")
        self.nine = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("9"))
        self.nine.setGeometry(QtCore.QRect(110, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.nine.setFont(font)
        self.nine.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#nine{\n"
"   border: 1px solid gray;\n"
"}\n"
"#nine:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.nine.setObjectName("nine")
        self.eight = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("8"))
        self.eight.setGeometry(QtCore.QRect(60, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.eight.setFont(font)
        self.eight.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#eight{\n"
"   border: 1px solid gray;\n"
"}\n"
"#eight:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.eight.setObjectName("eight")
        self.ac = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("AC"))
        self.ac.setGeometry(QtCore.QRect(210, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.ac.setFont(font)
        self.ac.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#ac{\n"
"   border: 1px solid gray;\n"
"}\n"
"#ac:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.ac.setObjectName("ac")
        self.dell = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clear_pressed())
        self.dell.setGeometry(QtCore.QRect(160, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.dell.setFont(font)
        self.dell.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#dell{\n"
"   border: 1px solid gray;\n"
"}\n"
"#dell:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.dell.setObjectName("dell")
        self.x10x = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("*10^"))
        self.x10x.setGeometry(QtCore.QRect(160, 380, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.x10x.setFont(font)
        self.x10x.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#x10x{\n"
"   border: 1px solid gray;\n"
"}\n"
"#x10x:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.x10x.setObjectName("x10x")
        self.equal = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.equal_pressed())
        self.equal.setGeometry(QtCore.QRect(210, 380, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.equal.setFont(font)
        self.equal.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#equal{\n"
"   border: 1px solid gray;\n"
"}\n"
"#equal:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.equal.setObjectName("equal")
        self.pm = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pm_func("+/-"))
        self.pm.setGeometry(QtCore.QRect(10, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.pm.setFont(font)
        self.pm.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#pm{\n"
"   border: 1px solid gray;\n"
"}\n"
"#pm:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.pm.setObjectName("pm")
        self.percent = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pm_func("%"))
        self.percent.setGeometry(QtCore.QRect(61, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.percent.setFont(font)
        self.percent.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#percent{\n"
"   border: 1px solid gray;\n"
"}\n"
"#percent:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.percent.setObjectName("percent")
        self.obracket = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("("))
        self.obracket.setGeometry(QtCore.QRect(111, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.obracket.setFont(font)
        self.obracket.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#obracket{\n"
"   border: 1px solid gray;\n"
"}\n"
"#obracket:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.obracket.setObjectName("obracket")
        self.cbracket = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed(")"))
        self.cbracket.setGeometry(QtCore.QRect(160, 200, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.cbracket.setFont(font)
        self.cbracket.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#cbracket{\n"
"   border: 1px solid gray;\n"
"}\n"
"#cbracket:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.cbracket.setObjectName("cbracket")
        self.pq = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pq_func())
        self.pq.setGeometry(QtCore.QRect(210, 201, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.pq.setFont(font)
        self.pq.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#pq{\n"
"   border: 1px solid gray;\n"
"}\n"
"#pq:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.pq.setObjectName("pq")
        self.tan = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.tan_func())
        self.tan.setGeometry(QtCore.QRect(111, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.tan.setFont(font)
        self.tan.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#tan{\n"
"   border: 1px solid gray;\n"
"}\n"
"#tan:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.tan.setObjectName("tan")
        self.sin = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.sin_func())
        self.sin.setGeometry(QtCore.QRect(10, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.sin.setFont(font)
        self.sin.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#sin{\n"
"   border: 1px solid gray;\n"
"}\n"
"#sin:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.sin.setObjectName("sin")
        self.cos1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.acos_func())
        self.cos1.setGeometry(QtCore.QRect(210, 171, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.cos1.setFont(font)
        self.cos1.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#cos1{\n"
"   border: 1px solid gray;\n"
"}\n"
"#cos1:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.cos1.setObjectName("cos1")
        self.cos = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.cos_func())
        self.cos.setGeometry(QtCore.QRect(61, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.cos.setFont(font)
        self.cos.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#cos{\n"
"   border: 1px solid gray;\n"
"}\n"
"#cos:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.cos.setObjectName("cos")
        self.sin1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.asin_func())
        self.sin1.setGeometry(QtCore.QRect(160, 170, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.sin1.setFont(font)
        self.sin1.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#sin1{\n"
"   border: 1px solid gray;\n"
"}\n"
"#sin1:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.sin1.setObjectName("sin1")
        self.square = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("^2"))
        self.square.setGeometry(QtCore.QRect(60, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.square.setFont(font)
        self.square.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#square{\n"
"   border: 1px solid gray;\n"
"}\n"
"#square:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.square.setObjectName("square")
        self.squareroot = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("^(1/2)"))
        self.squareroot.setGeometry(QtCore.QRect(10, 140, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.squareroot.setFont(font)
        self.squareroot.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#squareroot{\n"
"   border: 1px solid gray;\n"
"}\n"
"#squareroot:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.squareroot.setObjectName("squareroot")
        self.log = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.log_func())
        self.log.setGeometry(QtCore.QRect(159, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.log.setFont(font)
        self.log.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#log{\n"
"   border: 1px solid gray;\n"
"}\n"
"#log:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.log.setObjectName("log")
        self.tan1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.atan_func())
        self.tan1.setGeometry(QtCore.QRect(210, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.tan1.setFont(font)
        self.tan1.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#tan1{\n"
"   border: 1px solid gray;\n"
"}\n"
"#tan1:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.tan1.setObjectName("tan1")
        self.xpowery = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("^"))
        self.xpowery.setGeometry(QtCore.QRect(110, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.xpowery.setFont(font)
        self.xpowery.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#xpowery{\n"
"   border: 1px solid gray;\n"
"}\n"
"#xpowery:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.xpowery.setObjectName("xpowery")
        self.abs = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.ABS())
        self.abs.setGeometry(QtCore.QRect(10, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.abs.setFont(font)
        self.abs.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#abs{\n"
"   border: 1px solid gray;\n"
"}\n"
"#abs:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.abs.setObjectName("abs")
        self.x1 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("^(-1)"))
        self.x1.setGeometry(QtCore.QRect(110, 110, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.x1.setFont(font)
        self.x1.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#x1{\n"
"   border: 1px solid gray;\n"
"}\n"
"#x1:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.x1.setObjectName("x1")
        self.exp = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("exp"))
        self.exp.setGeometry(QtCore.QRect(159, 110, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.exp.setFont(font)
        self.exp.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#exp{\n"
"   border: 1px solid gray;\n"
"}\n"
"#exp:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.exp.setObjectName("exp")
        self.cube = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("^3"))
        self.cube.setGeometry(QtCore.QRect(60, 110, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.cube.setFont(font)
        self.cube.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#cube{\n"
"   border: 1px solid gray;\n"
"}\n"
"#cube:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.cube.setObjectName("cube")
        self.cubic = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("^(1/3)"))
        self.cubic.setGeometry(QtCore.QRect(210, 110, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.cubic.setFont(font)
        self.cubic.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#cubic{\n"
"   border: 1px solid gray;\n"
"}\n"
"#cubic:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.cubic.setObjectName("cubic")
        self.pi = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.digit_pressed("pi"))
        self.pi.setGeometry(QtCore.QRect(61, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.pi.setFont(font)
        self.pi.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#pi{\n"
"   border: 1px solid gray;\n"
"}\n"
"#pi:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.pi.setObjectName("pi")
        self.tanh = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.tanh_func())
        self.tanh.setGeometry(QtCore.QRect(211, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.tanh.setFont(font)
        self.tanh.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#tanh{\n"
"   border: 1px solid gray;\n"
"}\n"
"#tanh:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.tanh.setObjectName("tanh")
        self.sinh = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.sinh_func())
        self.sinh.setGeometry(QtCore.QRect(111, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.sinh.setFont(font)
        self.sinh.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#sinh{\n"
"   border: 1px solid gray;\n"
"}\n"
"#sinh:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.sinh.setObjectName("sinh")
        self.factorial = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.factorial1())
        self.factorial.setGeometry(QtCore.QRect(11, 80, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.factorial.setFont(font)
        self.factorial.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#factorial{\n"
"   border: 1px solid gray;\n"
"}\n"
"#factorial:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.factorial.setObjectName("factorial")
        self.cosh = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.cosh_func())
        self.cosh.setGeometry(QtCore.QRect(160, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(10)
        self.cosh.setFont(font)
        self.cosh.setStyleSheet("/* Digits 0-9 Stylesheet */\n"
"#cosh{\n"
"   border: 1px solid gray;\n"
"}\n"
"#cosh:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"/* End Digits 0-9 Stylesheet */")
        self.cosh.setObjectName("cosh")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def digit_pressed(self, press):
            if self.result.text() != "0":
                self.expression.setText("0")
                self.result.setText("0")
            if press == "AC":
                self.expression.setText("0")
            else:
                if self.expression.text() == "0":
                    self.expression.setText("")
                newLabel = self.expression.text() + press
                self.expression.setText(newLabel)
    def clear_pressed(self):
        newlabel = self.expression.text()
        newlabel = newlabel[:-1]
        self.expression.setText(newlabel)

    def factorial1(self):
        num = int(self.result.text())
        self.result.setText(str(math.factorial(num)))

    def equal_pressed(self):
        try:
            exp = self.expression.text()
            exp = exp.replace("pi", "3.1415926")
            exp = exp.replace("exp", "2.71828")
            exp = exp.replace("^", "**")
            results = eval(exp)
            if (results - int(results) == 0):
                self.result.setText(str(int(results)))
            else:
                result_format = format(results, ".8f")
                string = str(result_format).split(".")
                decimal_part = string[1]
                while(decimal_part[-1] == "0"):
                    decimal_part = decimal_part[:-1]
                self.result.setText(f"{string[0]}.{decimal_part}")
        except:
            self.result.setText("Something wrong happened")

    def decimal_pressed(self):
        self.expression.setText(f"{self.expression.text()}.")

    def sin_func(self):
        try:
            num = float(self.result.text())
            num = (num*math.pi) / 180
            self.result.setText(f"{math.sin(num)}")
        except:
            self.result.setText("Not possible")

    def cos_func(self):
        try:
            num = float(self.result.text())
            num = (num*math.pi) / 180
            self.result.setText(f"{math.cos(num)}")
        except:
            self.result.setText("Not possible")

    def tan_func(self):
        try:
            num = float(self.result.text())
            num = (num*math.pi) / 180
            self.result.setText(f"{math.tan(num)}")
        except:
            self.result.setText("Not possible")

    def asin_func(self):
        try:
            num = math.asin(float(self.result.text()))
            num = (num * 180) / math.pi
            self.result.setText(f"{num}")
        except:
            self.result.setText("Not possible")

    def acos_func(self):
        try:
            num = math.acos(float(self.result.text()))
            num = (num * 180) / math.pi
            self.result.setText(f"{num}")
        except:
            self.result.setText("Not possible")

    def atan_func(self):
        try:
            num = math.atan(float(self.result.text()))
            num = (num * 180) / math.pi
            self.result.setText(f"{num}")
        except:
            self.result.setText("Not possible")

    def sinh_func(self):
        try:
            num = float(self.result.text())
            num = (num*math.pi) / 180
            self.result.setText(f"{math.sinh(num)}")
        except:
            self.result.setText("Not possible")

    def cosh_func(self):
        try:
            num = float(self.result.text())
            num = (num*math.pi) / 180
            self.result.setText(f"{math.cosh(num)}")
        except:
            self.result.setText("Not possible")

    def tanh_func(self):
        try:
            num = float(self.result.text())
            num = (num*math.pi) / 180
            self.result.setText(f"{math.tanh(num)}")
        except:
            self.result.setText("Not possible")

    def ABS(self):
        if "-" in self.result.text():
            self.result.setText(self.result.text()[1:])

    def log_func(self):
        self.result.setText(f"{math.log10(float(self.result.text()))}")

    def pq_func(self):
        try:
            if "/" in self.result.text():
                results = self.result.text().split("/")
                self.result.setText(str(float(results[0]) / float(results[1])))
            else:
                results = self.result.text()
                string_res = results.split(".")
                len_res = len(string_res[1])
                multi = "1"
                i = 0
                while(i < len_res):
                    multi = multi + "0"
                    i = i + 1
                results = float(results) * int(multi)
                gcd = math.gcd(int(results), int(multi))
                neum = results / gcd
                denu = int(multi) / gcd
                self.result.setText(f"{int(neum)}/{int(denu)}")
        except:
            self.result.setText("Invalid input")
    def pm_func(self, press):
        if "+/-" in press:
            self.result.setText(str(float(self.result.text()) * -1))
        elif "%" in press:
            self.result.setText(str(float(self.result.text()) * 0.01))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.expression.setText(_translate("MainWindow", "0"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.dot.setText(_translate("MainWindow", "."))
        self.one.setText(_translate("MainWindow", "1"))
        self.two.setText(_translate("MainWindow", "2"))
        self.three.setText(_translate("MainWindow", "3"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.six.setText(_translate("MainWindow", "6"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.multiply.setText(_translate("MainWindow", "x"))
        self.four.setText(_translate("MainWindow", "4"))
        self.five.setText(_translate("MainWindow", "5"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.ac.setText(_translate("MainWindow", "AC"))
        self.dell.setText(_translate("MainWindow", "DEL"))
        self.x10x.setText(_translate("MainWindow", "x10^"))
        self.equal.setText(_translate("MainWindow", "="))
        self.pm.setText(_translate("MainWindow", "+/-"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.obracket.setText(_translate("MainWindow", "("))
        self.cbracket.setText(_translate("MainWindow", ")"))
        self.pq.setText(_translate("MainWindow", "p/q"))
        self.tan.setText(_translate("MainWindow", "tan"))
        self.sin.setText(_translate("MainWindow", "sin"))
        self.cos1.setText(_translate("MainWindow", "cos^-1"))
        self.cos.setText(_translate("MainWindow", "cos"))
        self.sin1.setText(_translate("MainWindow", "sin^-1"))
        self.square.setText(_translate("MainWindow", "x^2"))
        self.squareroot.setText(_translate("MainWindow", "x^0.5"))
        self.log.setText(_translate("MainWindow", "log"))
        self.tan1.setText(_translate("MainWindow", "tan^-1"))
        self.xpowery.setText(_translate("MainWindow", "x^y"))
        self.abs.setText(_translate("MainWindow", "Abs"))
        self.x1.setText(_translate("MainWindow", "x^-1"))
        self.exp.setText(_translate("MainWindow", "Exp"))
        self.cube.setText(_translate("MainWindow", "x^3"))
        self.cubic.setText(_translate("MainWindow", "x^0.3"))
        self.pi.setText(_translate("MainWindow", "pi"))
        self.tanh.setText(_translate("MainWindow", "tanh"))
        self.sinh.setText(_translate("MainWindow", "sinh"))
        self.factorial.setText(_translate("MainWindow", "x!"))
        self.cosh.setText(_translate("MainWindow", "cosh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
